apiVersion: v1
kind: Service
metadata:
  name: backend-service  # Unique service name for the first backend instance
spec:
  type: ClusterIP
  selector:
    app: flask-backend
  ports:
    - port: 5001  # The service port exposed internally within the Kubernetes cluster
      targetPort: 5001  # The port on the container