apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend-deployment  # Unique name for the backend deployment
spec:
  replicas: 3  # Adjust replica count as desired
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
      - name: flask-backend
        image: prajwal111299/flask-backend:1.0.0  # Replace with your actual Docker Hub username
        ports:
        - containerPort: 5001
